version: '2'

services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=secrect
      - POSTGRES_USER=postgres
    container_name: 'postgres'
    image: 'postgres:9.5.3'
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'

  redis:
    container_name: 'redis'
    image: 'redislabs/redisearch:latest'
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - 'redisdata:/data'

volumes:
  pgdata:
  redisdata: